User authentication using Devise gem
tayyab-devsinc/tyb_demo_app pull request #1
Opened 2020-08-20 09:40 UTC by tayyab-devsinc

- User Authentication completed using Devise gem.
- Added Bootstrap for User Authentication pages

2020-08-21 10:15 UTC, omijaved requested changes
Remove the bin files. These files should not be committed.
We will go over the README file sometime in the future. For now it's good to go.

2020-08-21 10:15 UTC, omijaved commented on Gemfile
> +# gem 'bootstrap', '~> 4.5.0'
remove the gems that are not being used instead of commenting them.

2020-08-21 10:15 UTC, omijaved commented on app/controllers/registrations_controller.rb
> +private
add a space below such access modifier in a given controller.

2020-08-21 10:15 UTC, omijaved commented on app/controllers/registrations_controller.rb
> +end
add space between two functions

2020-08-21 10:15 UTC, omijaved commented on app/controllers/registrations_controller.rb
> +end
always add extra line at the end of file

2020-08-21 10:15 UTC, omijaved commented on app/controllers/application_controller.rb
> +    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:profile_photo])
apply proper spacing here

2020-08-21 10:15 UTC, omijaved commented on app/models/user.rb
> +  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
remove commented code unless it can be of use in future.

2020-08-21 10:15 UTC, omijaved commented on app/models/user.rb
> +  validates_integrity_of  :profile_photo
spacing should be consistent throughout.

2020-08-21 10:15 UTC, omijaved commented on app/controllers/registrations_controller.rb
> +private
why this private is defined outside of the scope of controller?

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/confirmations/new.html.erb
> +  <%= render "devise/shared/error_messages", resource: resource %>
use single quotes for simple strings.

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/confirmations/new.html.erb
> +  <div class="field">
use single quote

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/confirmations/new.html.erb
> +    <%= f.email_field :email, autofocus: true, autocomplete: "email", value: (resource.pending_reconfirmation? ? resource.unconfirmed_email : resource.email) %>
use single quote

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/confirmations/new.html.erb
> +    <%= f.submit "Resend confirmation instructions" %>
use single quote

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/confirmations/new.html.erb
> +<%= render "devise/shared/links" %>
use single quote

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/mailer/email_changed.html.erb
> +<% if @resource.try(:unconfirmed_email?) %>
prefer to use safe navigation instead of try

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/passwords/edit.html.erb
> +  <%= render "devise/shared/error_messages", resource: resource %>
use single quotes throughout this file

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/passwords/new.html.erb
> +  <%= render "devise/shared/error_messages", resource: resource %>
use single quotes throughout this file

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/registrations/edit.html.erb
> +<div class="col-md-4">
indent properly

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/registrations/edit.html.erb
> +<div class="col-md-4">
throughout this file

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/registrations/edit.html.erb
> +<div class="col-md-4">
also use single quotes unless you are doing string interpolation

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/registrations/new.html.erb
> +<div class="row">
indent properly and use single quotes throughout this file.

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/sessions/new.html.erb
> +<div class="row">
indent properly and use single quotes throughout the file.

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/sessions/new.html.erb
> +</div>
add extra line at the end of file.

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/shared/_error_messages.html.erb
> +<% if resource.errors.any? %>
single quotes!

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/shared/_links.html.erb
> +<%- if controller_name != 'sessions' %>
single quotes!

2020-08-21 10:15 UTC, omijaved commented on app/views/devise/unlocks/new.html.erb
> +<h2>Resend unlock instructions</h2>
single quotes!

2020-08-21 10:15 UTC, omijaved commented on app/views/layouts/_footer.html.erb
> +<footer class="footer">
single quotes!

2020-08-21 10:15 UTC, omijaved commented on app/views/layouts/_footer.html.erb
> +<small>
indent this file properly

2020-08-21 10:15 UTC, omijaved commented on app/views/layouts/_footer.html.erb
> +</footer>
add extra line

2020-08-21 10:15 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +<header class="navbar navbar-fixed-top navbar-inverse">
use single quotes and indent this file properly

2020-08-21 10:15 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +<li class="dropdown">
apply proper spacing

2020-08-21 10:15 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +<a href="#" class="dropdown-toggle" data-toggle="dropdown">
apply spacing

2020-08-21 10:15 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +Account <b class="caret"></b>
spacing here as well and in the remaining file too

2020-08-21 10:15 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +</header>
add extra line

2020-08-21 10:15 UTC, omijaved commented on app/views/layouts/_rails_default.html.erb
> + <%= csrf_meta_tags %>
fix indentation of this file

2020-08-21 10:15 UTC, omijaved commented on app/views/layouts/_rails_default.html.erb
> +    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
use consistent spacing

2020-08-21 10:15 UTC, omijaved commented on app/views/layouts/_rails_default.html.erb
> +    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
add extra line

2020-08-21 10:15 UTC, omijaved commented on app/views/layouts/application.html.erb
> +    <title><%= full_title(yield(:title))%></title>
fix spacing

2020-08-21 10:15 UTC, omijaved commented on app/views/layouts/application.html.erb
> +<div class="container">
fix indentation of this file and spacing

2020-08-21 10:15 UTC, omijaved commented on app/views/static_pages/home.html.erb
> +HOME
add extra line

2020-08-21 10:15 UTC, omijaved commented on config/locales/devise.en.yml
> +# Additional translations at https://github.com/heartcombo/devise/wiki/I18n
these kind of strings should also be enclosed in single quotes but you can just let it be how it is currently.

2020-08-21 10:15 UTC, omijaved commented on config/routes.rb
> +  root 'static_pages#home'
its better to define root at the end of the file

2020-08-21 10:15 UTC, omijaved commented on config/routes.rb
> +  get '/home', to: 'static_pages#home'
no need for line spacing between routes that are grouped in terms of their functionality like these

2020-08-21 10:15 UTC, omijaved commented on config/routes.rb
>    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
remove this

2020-08-21 10:15 UTC, omijaved commented on db/schema.rb
> +    t.string "type"
I would recommend you to look into enums in detail and see how they can better suit you for this purpose rather than string. String is fine but you should definitely look that up as well.

2020-08-21 10:15 UTC, omijaved commented on app/assets/stylesheets/custom.scss
> +/* mixins, variables, etc. */
remove this

2020-08-21 10:15 UTC, omijaved commented on app/assets/stylesheets/custom.scss
> +@import "bootstrap-sprockets";
use single quotes

2020-08-21 10:15 UTC, omijaved commented on app/assets/stylesheets/custom.scss
> +@import "bootstrap";
single quote

2020-08-21 10:15 UTC, omijaved commented on app/assets/stylesheets/custom.scss
> +    }
fix indentation

2020-08-21 10:15 UTC, omijaved commented on app/assets/stylesheets/custom.scss
> +    border-box;
the property should be on the same line and not on new.

2020-08-21 10:15 UTC, omijaved commented on app/assets/stylesheets/custom.scss
> +    border-box;
fix styling

2020-08-21 10:15 UTC, omijaved commented on app/assets/stylesheets/custom.scss
> +/* universal */
remove this

2020-08-21 10:15 UTC, omijaved commented on app/assets/stylesheets/custom.scss
> +overflow: auto;
fix indentation

2020-08-21 10:15 UTC, omijaved commented on app/assets/stylesheets/custom.scss
> +resize: vertical;
fix indentation here and throughout this file

2020-08-21 10:15 UTC, omijaved commented on app/assets/stylesheets/custom.scss
> +@import "bootstrap-sprockets";
instead of adding every style in this file. You should define separate scss files for each controller and then write the styling of each controller specific pages in that specific scss file.

And if you want to define a style that should be use throughout the application than use `application.scss` for that purpose.

2020-08-21 10:15 UTC, omijaved commented on app/assets/stylesheets/custom.scss
> +/* typography */
remove

2020-08-21 10:15 UTC, omijaved commented on app/assets/stylesheets/custom.scss
> +}
add extra line

2020-08-21 10:47 UTC, tayyab-devsinc commented on app/views/devise/confirmations/new.html.erb
> +  <%= render "devise/shared/error_messages", resource: resource %>
This code is auto-generated by devise, should I change all devise files myself to make all double quoted strings to single quoted.

2020-08-21 13:07 UTC, tayyab-devsinc commented on config/routes.rb
>    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
What to remove here?

2020-08-21 13:14 UTC, tayyab-devsinc commented on app/views/layouts/_header.html.erb
> +<header class="navbar navbar-fixed-top navbar-inverse">
Just to confirm, should the classes of bootstrap also in single quoted?

2020-08-23 12:12 UTC, omijaved requested changes

2020-08-23 12:12 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +<header class="navbar navbar-fixed-top navbar-inverse">
yes

2020-08-23 12:12 UTC, omijaved commented on app/views/layouts/_rails_default.html.erb
> +    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
This is still pending!

2020-08-23 12:12 UTC, omijaved commented on app/views/layouts/application.html.erb
> +<div class="container">
this is still pending!

2020-08-23 12:12 UTC, omijaved commented on config/routes.rb
> +  root 'static_pages#home'
add space above as root is a separate group than those above it.

2020-08-24 10:24 UTC, omijaved requested changes

2020-08-24 10:24 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +<header class='navbar navbar-fixed-top navbar-inverse'>
add proper spacing.
`class= ''`

2020-08-24 10:24 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +  <div class='container'>
same here as above!

2020-08-24 10:24 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +      <ul class='nav navbar-nav navbar-right'>
same here as above!

2020-08-24 10:24 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +          <li class='dropdown'>
same here as above

2020-08-24 10:24 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +            <a href='#' class='dropdown-toggle' data-toggle="dropdown">
same here

2020-08-24 10:24 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +              Account <b class='caret'></b>
same here

2020-08-24 10:24 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +            <ul class='dropdown-menu'>
same here

2020-08-24 10:24 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +              <li class='divider'></li>
same here

2020-08-24 10:24 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +              </ul>
fix indentation

2020-08-24 10:24 UTC, omijaved commented on app/views/layouts/_header.html.erb
> +          <li><%= link_to "Log in", user_session_path %></li>
single quotes

2020-08-24 10:24 UTC, omijaved commented on app/views/layouts/application.html.erb
> +<%= render 'layouts/header' %>
indent properly under body tag

2020-08-24 10:24 UTC, omijaved commented on app/views/layouts/application.html.erb
> +<div class='container'>
add space

2020-08-24 10:24 UTC, omijaved commented on app/views/layouts/application.html.erb
> +    <div class="alert alert-<%= message_type %>"><%= message %></div>
add space

2020-08-24 10:24 UTC, omijaved commented on app/views/layouts/mailer.html.erb
> +    <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
add space

2020-08-24 12:38 UTC, omijaved approved these changes
+1

2020-08-24 12:38 UTC, merged